# Generated by Django 5.0.4 on 2024-07-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_hired',
        ),
    ]
