# Generated by Django 5.0.4 on 2024-07-07 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_date_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_hired',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
