# Generated by Django 5.0.4 on 2024-07-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('rhino', 'RHINO'), ('leopard', 'LEOPARD'), ('mamba', 'MAMBA'), ('Zebra', 'ZEBRA'), ('Chameleon', 'CHAMELEON')], max_length=100)),
                ('flower_type', models.CharField(choices=[('roses', 'ROSES'), ('hypecerum', 'HYPECERUM')])),
                ('growing_style', models.CharField(choices=[('field_growing', 'FIELD_GROWING'), ('bed_growing', 'BED_GROWING')])),
                ('area', models.CharField(choices=[('50 by 50', '50 BY 50'), ('50 by 100', '50 BY 100'), ('100 by 100', '100 BY 100'), ('200 by 200', '200 BY 200')])),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('light_intensity', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
