# Generated by Django 5.0.4 on 2024-07-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouses',
            fields=[
                ('greenhouse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('rhino', 'RHINO'), ('leopard', 'LEOPARD'), ('mamba', 'MAMBA'), ('Zebra', 'ZEBRA'), ('Chameleon', 'CHAMELEON')], default=('rhino', 'RHINO'), max_length=100)),
                ('flower_type', models.CharField(choices=[('roses', 'ROSES'), ('hypecerum', 'HYPECERUM')], default=('roses', 'ROSES'))),
                ('growing_style', models.CharField(choices=[('field_growing', 'FIELD_GROWING'), ('bed_growing', 'BED_GROWING')], default=('field_growing', 'FIELD_GROWING'))),
                ('area', models.CharField(choices=[('50 by 50', '50 BY 50'), ('50 by 100', '50 BY 100'), ('100 by 100', '100 BY 100'), ('200 by 200', '200 BY 200')], default=('50 by 50', '50 BY 50'))),
                ('temperature', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('light_intensity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
